import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'My Wish List',
    description: 'Generated by create next app'
}

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='es'>
            <body
                className={`${inter.className} flex min-h-dvh w-dvw items-center justify-center bg-slate-50`}>
                {children}
            </body>
        </html>
    )
}
